### ISSUE TITLE
Umbrella Issue for Features of CLI MVP version

### ISSUE THREAD

**Issue by wonderflow** [cloud-native-application/RudrX#55]
# Basic Usage

- [x]   version:     show your current cli version #40
- [x]   env:     set your environment #57
- [x]   ls:  list your apps  https://github.com/cloud-native-application/RudrX/issues/34 https://github.com/cloud-native-application/RudrX/pull/56 
- [x]   show:     get detail spec of your app https://github.com/cloud-native-application/RudrX/issues/58  @erdun 
- [x]   status:     get running status of your app https://github.com/cloud-native-application/RudrX/issues/59
- [x]   delete:     remove your app https://github.com/cloud-native-application/RudrX/issues/6
- [x]   workloads:     list all workload types #62
- [x]  `rudr <workload-type>: run <appname>` : eg:   rudr deployment:run myapp #63
- [x]   traits:    list all trait types  #8 #60 
- [x]  `rudr <trait> <appname>`:    eg:	rudr route myapp --domain myapp.com  https://github.com/cloud-native-application/RudrX/issues/18
    * [x] bind #72 
    * [x] unbind  #73
- [x] Update Readme

#  Advanced Usage:

- [x] support CUE as definition template file #35 @wonderflow 
- [x]   ~appset:   bundle your apps~ #20 （we don't support this feature in MVP）
- [x]   ~snapshot:     make a snapshort for your app~  #37 （we don't support this feature in MVP）
- [x]   plugins:   discovery/install plugins https://github.com/cloud-native-application/RudrX/issues/19 @zzxwill 
- [x]   dashboard:     run a dashboard locally @ryanzhang-oss  https://github.com/cloud-native-application/RudrX/pull/154
- [x]   completion:     build auto completion shell script #88 @sunny0826 
- [x]   admin:   administrator operations, like install/init  https://github.com/cloud-native-application/RudrX/issues/12

**Comment by sunny0826** [comment]
add a issue #88  for completion and accept it

**Comment by wonderflow** [comment]
Closing as all of them has been done.
